### ISSUE TITLE
BWA on MACBOOK M1 chip

### ISSUE THREAD

**Issue by khanshahan** [smikkelsendk/bwa-for-arm#1]
Can you please tell me are these patches designed to enable BWA to compile on Apple M1 processor which is arm based ? If yes, how can I apply it on BWA? The make file fails.

**Comment by smikkelsendk** [comment]
Hi, please try the following and let me know the result:

Download https://github.com/smikkelsendk/bwa-for-arm/blob/master/src.tar.gz
Extract bwa-0.7.17-neon 
Inside the bwa-0.7.17-neon, run:
clang -O2 -std=gnu90 -DHAVE_PTHREAD *.c -o bwa -lm -pthread -lrt
If all goes well, you should have an executable named bwa

**Comment by smikkelsendk** [comment]
I have added binary to https://github.com/smikkelsendk/bwa-for-arm/tree/master/bin

**Comment by BirkirRey** [comment]
Hi,
I tried to compile from the bwa-0.7.17-neon directory as you instructed, but got errors.
But the binary seems to work fine.
I am working on a recent M1 macbook

**Comment by limwaifeng** [comment]
Hi, I'm new to bioinformatic and using M1 MacBook. Can I have a step-by-step how to install this bwa? Appreciate that.

**Comment by smikkelsendk** [comment]
Download  bwa0717-mac-arm64 
Make it executable (chmod a+x  bwa0717-mac-arm64)
Execute it from shell ./bwa0717-mac-arm64

**Comment by jianshu93** [comment]
I have this error on M1 pro but the binary works:

gzlib.c:252:9: error: implicit declaration of function 'lseek' [-Werror,-Wimplicit-function-declaration]
        LSEEK(state->fd, 0, SEEK_END);  /* so gzoffset() is correct */
        ^
gzlib.c:14:17: note: expanded from macro 'LSEEK'
#  define LSEEK lseek
                ^
gzlib.c:252:9: note: did you mean 'fseek'?
gzlib.c:14:17: note: expanded from macro 'LSEEK'
#  define LSEEK lseek
                ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdio.h:162:6: note: 'fseek' declared here
int      fseek(FILE *, long, int);
         ^
gzlib.c:258:24: error: implicit declaration of function 'lseek' [-Werror,-Wimplicit-function-declaration]
        state->start = LSEEK(state->fd, 0, SEEK_CUR);
                       ^
gzlib.c:14:17: note: expanded from macro 'LSEEK'
#  define LSEEK lseek
                ^
gzlib.c:359:9: error: implicit declaration of function 'lseek' [-Werror,-Wimplicit-function-declaration]
    if (LSEEK(state->fd, state->start, SEEK_SET) == -1)
        ^
gzlib.c:14:17: note: expanded from macro 'LSEEK'
#  define LSEEK lseek
                ^
gzlib.c:400:15: error: implicit declaration of function 'lseek' [-Werror,-Wimplicit-function-declaration]
        ret = LSEEK(state->fd, offset - state->x.have, SEEK_CUR);
              ^
gzlib.c:14:17: note: expanded from macro 'LSEEK'
#  define LSEEK lseek
                ^
gzlib.c:496:14: error: implicit declaration of function 'lseek' [-Werror,-Wimplicit-function-declaration]
    offset = LSEEK(state->fd, 0, SEEK_CUR);
             ^
gzlib.c:14:17: note: expanded from macro 'LSEEK'
#  define LSEEK lseek
                ^
5 errors generated.
gzread.c:35:15: error: implicit declaration of function 'read' [-Werror,-Wimplicit-function-declaration]
        ret = read(state->fd, buf + *have, get);
              ^
gzread.c:35:15: note: did you mean 'fread'?
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdio.h:158:9: note: 'fread' declared here
size_t   fread(void * __restrict __ptr, size_t __size, size_t __nitems, FILE * __restrict __stream);
         ^
gzread.c:651:11: error: implicit declaration of function 'close' [-Werror,-Wimplicit-function-declaration]
    ret = close(state->fd);
          ^
2 errors generated.
gzwrite.c:89:20: error: implicit declaration of function 'write' [-Werror,-Wimplicit-function-declaration]
            writ = write(state->fd, strm->next_in, put);
                   ^
gzwrite.c:89:20: note: did you mean 'fwrite'?
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdio.h:165:9: note: 'fwrite' declared here
size_t   fwrite(const void * __restrict __ptr, size_t __size, size_t __nitems, FILE * __restrict __stream) __DARWIN_ALIAS(fwrite);
         ^
gzwrite.c:110:24: error: implicit declaration of function 'write' [-Werror,-Wimplicit-function-declaration]
                writ = write(state->fd, state->x.next, put);
                       ^
gzwrite.c:661:9: error: implicit declaration of function 'close' [-Werror,-Wimplicit-function-declaration]
    if (close(state->fd) == -1)
        ^
3 errors generated.
kopen.c:295:10: warning: 'vfork' is deprecated: Use posix_spawn or fork [-Wdeprecated-declarations]
                        pid = vfork();
                              ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/unistd.h:604:1: note: 'vfork' has been explicitly marked deprecated here
__deprecated_msg("Use posix_spawn or fork")
^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/cdefs.h:208:48: note: expanded from macro '__deprecated_msg'
        #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
                                                      ^
1 warning generated.


Thanks,

Jianshu

**Comment by smikkelsendk** [comment]
in gzguts.h add:
#include <unistd.h>

Compile with:
clang -O2 -target arm64-apple-macos11 -std=gnu90 -DHAVE_PTHREAD  *.c -o bwa-mac-arm64 -lm -lz -pthread

**Comment by jianshu93** [comment]
Hello Thanks!

Solved but with this warning:

kopen.c:295:10: warning: 'vfork' is deprecated: Use posix_spawn or fork [-Wdeprecated-declarations]
                        pid = vfork();
                              ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/unistd.h:604:1: note: 'vfork' has been explicitly marked deprecated here
__deprecated_msg("Use posix_spawn or fork")
^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/cdefs.h:208:48: note: expanded from macro '__deprecated_msg'
        #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
                                                      ^
1 warning generated.


Thanks,

Jianshu
