### ISSUE TITLE
Proper download of BWA binaries on MacOS (x86 and M1)

### ISSUE THREAD

**Issue by RandyHarr** [smikkelsendk/bwa-for-arm#2]
Do appreciate your port and making the binaries available.  They are an integral part of the WGS Extract tool and install available on Ubuntu, MacOS and Windows (see https://wgsextract.github.io/). Unfortunately, I was not aware until recently of your change to tar.gz files.  I have been scratching my head for a few hours now though.  I can download your binaries, for any platform on Windows and use 7Zip to unpack them.  But any download to MacOS (either through curl or Safari) yields a file that neither tar nor 7zip says is a valid archive.  (Just to make sure Apple's behind the scenes magic was not kicking in, I checked that it was not auto-decompressed on download and simply a plain tar file; not that either.)  Have you run into this with Monterrey or other releases on MacOS on either M1 or x86?  Did you create the tar in a Mac or maybe it was in Cygwin?  My experience is that tar and zip files created on Cygwin are not loadable on MacOS -- something in the bits set for file attributes that do not get handled properly at the MacOS end. As a result, I create all releases on Mac's for all platforms using 7zip. This seems to capture MacOS attributes appropriately so when unpacked on MacOS, everything is fine. I really do not want to get in the business of redistributing your binaries by having to download them to a windows machine and repacking for distribution from my server.  Any ideas?

**Comment by smikkelsendk** [comment]
I have recreated the tar.gz files with compatibility option. If this does not help, please show me the console output of running
tar xf bwa0717-mac-aarch64.tar.gz
and
gunzip bwa0717-mac-aarch64.tar.gz
tar xf bwa0717-mac-aarch64.tar

**Comment by RandyHarr** [comment]
That solved the problem.  And in fact, Safari now auto-uncompressed the file and leaves it as a .tar which can be easily extracted and run. Thanks.

Just for the record, here is the console output on an M1 Monterrey 12.3. And notice the last command. Something I neglected to do yesterday.  (od -c).  Although the file was around the same size as the compressed archive, it was nothing but a text HTML response saying the file was not in a format downloadable .... duh.  Should have picked up on that originally.

% tar -xf bwa0717-mac-aarch64-orig.tar.gz            
tar: Error opening archive: Unrecognized archive format
%  gunzip bwa0717-mac-aarch64-orig.tar.gz             
gunzip: bwa0717-mac-aarch64-orig.tar.gz: not in gzip format
% /opt/local/bin/7z x bwa0717-mac-aarch64-orig.tar.gz
7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=utf8,Utf16=on,HugeFiles=on,64 bits,8 CPUs LE)
Scanning the drive for archives:
1 file, 193402 bytes (189 KiB)
Extracting archive: bwa0717-mac-aarch64-orig.tar.gz
ERROR: bwa0717-mac-aarch64-orig.tar.gz
bwa0717-mac-aarch64-orig.tar.gz
Open ERROR: Can not open the file as [gzip] archive
ERRORS:
Is not archive
Can't open as archive: 1
Files: 0
Size:       0
Compressed: 0
% od -c bwa0717-mac-aarch64-orig.tar.gz | head
0000000   \n  \n  \n  \n  \n  \n   <   !   D   O   C   T   Y   P   E    
0000020    h   t   m   l   >  \n   <   h   t   m   l       l   a   n   g
0000040    =   "   e   n   "       d   a   t   a   -   c   o   l   o   r
0000060    -   m   o   d   e   =   "   a   u   t   o   "       d   a   t
0000100    a   -   l   i   g   h   t   -   t   h   e   m   e   =   "   l
0000120    i   g   h   t   "       d   a   t   a   -   d   a   r   k   -
0000140    t   h   e   m   e   =   "   d   a   r   k   "       >  \n    
0000160        <   h   e   a   d   >  \n                   <   m   e   t
0000200    a       c   h   a   r   s   e   t   =   "   u   t   f   -   8
0000220    "   >  \n           <   l   i   n   k       r   e   l   =   "
![image](https://user-images.githubusercontent.com/58348151/163145579-e9ceade9-6000-47f1-a908-92c7eba5e4e9.png)

Here are the URLs that work again (albeit with the added .tar.gz extension now):
    https://raw.githubusercontent.com/smikkelsendk/bwa-for-arm/master/bin/bwa0717-mac-aarch64.tar.gz
    https://github.com/smikkelsendk/bwa-for-arm/raw/master/bin/bwa0717-mac-aarch64.tar.gz
And my installer command working again:
    curl -kLC - --retry 5 -o bwa.tar.gz https://raw.githubusercontent.com/smikkelsendk/bwa-for-arm/master/bin/bwa0717-mac-aarch64.tar.gz
(duplicate for x86 version on Mac as well)

**Comment by smikkelsendk** [comment]
Good to hear it is working now. You need to use the link that starts with raw, otherwise you simply get a html page from github
